ARG BASED_ON="ubuntu:latest"
FROM $BASED_ON

# Ideally should be this line, but some systems have issues with mounting the docker socket
# so we leave it commented out for now.
# VOLUME [ "/var/run/docker.sock" ]

WORKDIR /working-env/docker/dood/base